name: Deploy Test

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  build:
    name: Build, push and run docker image
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mrstringer/punkbottest:latest

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PUNKBOTTEST_HOST }}
          username: ${{ secrets.PUNKBOTTEST_USER }}
          key:  ${{ secrets.PUNKBOTTEST_PRIVATE_SSH }}
          fingerprint: ${{ secrets.PUNKBOTTEST_FINGERPRINT }}
          port: ${{ secrets.PUNKBOTTEST_HOST_PORT }}
          script: |
            docker image pull mrstringer/punkbottest:latest
            docker container stop punkbottest
            docker container rm punkbottest
            docker container run -d --name punkbottest -v /home/sstringer/ptest/botcnf.yml:/app/botcnf.yml -e PUNKBOT_PASSWORD='${{ secrets.PUNKBOTTEST_BSKY_APP_PASSWORD }}' mrstringer/punkbottest

# docker run -d -v /home/sstringer/ptest/botcnf.yml:/app/botcnf.yml -e PUNKBOT_PASSWORD='yqhy-ckib-nyb4-kauv' mrstringer/punkbot