# .github/workflows/release.yaml
name: Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]  
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        build_command: make build
  
  build:
    name: Build, push and run docker image
    runs-on: ubuntu-latest
  
    steps:

      - name: Remote Access Test
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PUNKBOT_HOST }}
          username: ${{ secrets.PUNKBOT_USER }}
          port: ${{ secrets.PUNKBOT_HOST_PORT }}
          key:  ${{ secrets.PUNKBOT_PRIVATE_SSH }}
          script: date

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mrstringer/punkbot:latest

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PUNKBOT_HOST }}
          username: ${{ secrets.PUNKBOT_USER }}
          port: ${{ secrets.PUNKBOT_HOST_PORT }}
          key:  ${{ secrets.PUNKBOT_PRIVATE_SSH }}
          script: |
            docker image pull mrstringer/punkbot:latest
            docker container stop punkbot
            docker container rm punkbot
            docker container run -d --name punkbot -v /home/sstringer/ptest/botcnf.yml:/app/botcnf.yml -e PUNKBOT_PASSWORD='${{ secrets.PUNKBOT_BSKY_APP_PASSWORD }}' mrstringer/punkbot
